
modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/LakMoore/Smooth-Entity-Light/issues"

[[mods]]
	modId="sel"
	version="${file.jarVersion}"
	displayName="Smooth Entity Light"
	updateJSONURL="https://www.dropbox.com/s/sofgctc8w0w6gyx/SmoothEntityLight.json?dl=1"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/smooth-entity-light"
	logoFile="assets/sel/textures/gui/logo.png"
	credits="AtomicStryker; for his original work"
	authors="LakMoore"
	description='''
	Entities emit light... smoothed light!
	
	Originally inspired and forked from AtomicStryker's Dynamic Lights Mod.
	'''
	[[dependencies.sel]]
	    modId="forge"
	    mandatory=true
	    versionRange="[28,)"
	    ordering="NONE"
	    side="BOTH"
	[[dependencies.sel]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.14.4]"
	    ordering="NONE"
	    side="BOTH"
	    